<?php
// This file generated by Propel 1.6.6 convert-conf target
// from XML runtime conf file C:\AppServ\propel_app\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'comvi' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=comvi',
        'user' => 'root',
        'password' => '123456',
      ),
    ),
    'default' => 'comvi',
  ),
  'generator_version' => '1.6.6',
);
//$conf['classmap'] = include(__DIR__ . DS . 'classmap-propel-conf.php');
return $conf;